set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN P20 } [get_ports reset]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN Y18 } [get_ports clock]

set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  Y9 } [get_ports io_switch[23]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  W9 } [get_ports io_switch[22]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  Y7 } [get_ports io_switch[21]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  Y8 } [get_ports io_switch[20]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN AB8 } [get_ports io_switch[19]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN AA8 } [get_ports io_switch[18]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  V8 } [get_ports io_switch[17]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  V9 } [get_ports io_switch[16]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN AB6 } [get_ports io_switch[15]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN AB7 } [get_ports io_switch[14]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  V7 } [get_ports io_switch[13]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN AA6 } [get_ports io_switch[12]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  Y6 } [get_ports io_switch[11]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  T6 } [get_ports io_switch[10]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  R6 } [get_ports io_switch[ 9]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  V5 } [get_ports io_switch[ 8]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  U6 } [get_ports io_switch[ 7]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  W5 } [get_ports io_switch[ 6]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  W6 } [get_ports io_switch[ 5]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  U5 } [get_ports io_switch[ 4]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  T5 } [get_ports io_switch[ 3]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  T4 } [get_ports io_switch[ 2]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  R4 } [get_ports io_switch[ 1]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  W4 } [get_ports io_switch[ 0]]

set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN A18 } [get_ports io_dig_en[7]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN A20 } [get_ports io_dig_en[6]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN B20 } [get_ports io_dig_en[5]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN E18 } [get_ports io_dig_en[4]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN F18 } [get_ports io_dig_en[3]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN D19 } [get_ports io_dig_en[2]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN E19 } [get_ports io_dig_en[1]]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN C19 } [get_ports io_dig_en[0]]

set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN F15 } [get_ports io_DN_A ]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN F13 } [get_ports io_DN_B ]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN F14 } [get_ports io_DN_C ]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN F16 } [get_ports io_DN_D ]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN E17 } [get_ports io_DN_E ]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN C14 } [get_ports io_DN_F ]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN C15 } [get_ports io_DN_G ]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN E13 } [get_ports io_DN_DP]